export const SA_PROVINCES = [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "Northern Cape",
    "North West",
    "Western Cape"
]

export type SAProvince = typeof SA_PROVINCES[number];

export const SA_SUBURBS: Record<SAProvince, string[]> = {
   "Gauteng": [
    "Sandton", "Randburg", "Roodepoort", "Soweto", "Midrand", "Centurion",
    "Pretoria Central", "Menlyn", "Hatfield", "Brooklyn", "Arcadia", "Sunnyside",
    "Garsfontein", "Faerie Glen", "Lynnwood", "Waterkloof", "Moreleta Park",
    "Kempton Park", "Boksburg", "Benoni", "Alberton", "Germiston", "Edenvale",
    "Bedfordview", "Johannesburg CBD", "Rosebank", "Parktown", "Melville",
    "Northcliff", "Fourways", "Sunninghill", "Kyalami", "Bryanston",
    "Randpark Ridge", "Florida", "Krugersdorp", "Vereeniging", "Vanderbijlpark",
    "Orange Farm", "Tembisa", "Thokoza", "Katlehong", "Mamelodi", "Atteridgeville",
    "Soshanguve", "Akasia", "Wonderboom", "Montana", "Silverton", "Pretoria North",
    "Linksfield", "Sandhurst", "Hyde Park", "Morningside", "Lonehill",
    "Douglasdale", "Linbro Park", "Greenstone", "Modderfontein", "Olifantsfontein",
    "Vosloorus", "Daveyton", "Springs", "Nigel", "Heidelberg", "Lenasia",
  ],
  "Western Cape": [
    "Cape Town CBD", "Sea Point", "Green Point", "Camps Bay", "Clifton", "Bantry Bay",
    "Gardens", "Oranjezicht", "Tamboerskloof", "Claremont", "Kenilworth", "Wynberg",
    "Constantia", "Bishopscourt", "Newlands", "Rondebosch", "Mowbray", "Observatory",
    "Woodstock", "Salt River", "Bellville", "Durbanville", "Brackenfell", "Kuils River",
    "Stellenbosch", "Paarl", "Franschhoek", "Somerset West", "Strand", "Gordon's Bay",
    "Mitchells Plain", "Khayelitsha", "Gugulethu", "Langa", "Parow", "Goodwood",
    "Matroosfontein", "George", "Knysna", "Mossel Bay", "Oudtshoorn", "Hermanus",
    "Worcester", "Robertson", "Ceres", "Vredenburg", "Saldanha", "Plettenberg Bay",
    "Milnerton", "Table View", "Bloubergstrand", "Sunset Beach", "Edgemead",
    "Pinelands", "Athlone", "Kraaifontein", "Stikland", "Tygerberg", "Hout Bay",
    "Fish Hoek", "Simon's Town", "Muizenberg", "Tokai", "Bergvliet",
  ],
  "KwaZulu-Natal": [
    "Durban CBD", "Berea", "Morningside", "Musgrave", "Glenwood", "Umbilo",
    "Pinetown", "Westville", "Hillcrest", "Ballito", "Umhlanga", "La Lucia",
    "Durban North", "Phoenix", "Tongaat", "Umlazi", "KwaMashu", "Ntuzuma",
    "Pietermaritzburg", "Hilton", "Howick", "Richards Bay", "Empangeni", "Newcastle",
    "Ladysmith", "Port Shepstone", "Margate", "Amanzimtoti", "Prospecton", "Reunion",
    "Chatsworth", "Mount Edgecombe", "Verulam", "Stanger", "KwaDukuza", "Shelly Beach",
    "Scottburgh", "Pennington", "Ramsgate", "Uvongo", "Southbroom", "Hibberdene",
    "Mtubatuba", "Eshowe", "Ulundi", "Vryheid", "Dundee", "Estcourt", "Mooi River",
    "Underberg", "Kokstad", "Ixopo", "Mtunzini", "Mandeni", "Stanger Heights",
    "Umkomaas", "Kingsburgh", "Queensburgh", "Yellowwood Park", "Bluff",
  ],
  "Eastern Cape": [
    "Port Elizabeth CBD", "Gqeberha", "Summerstrand", "Humewood", "Walmer", "Newton Park",
    "Greenacres", "Mill Park", "Lorraine", "East London CBD", "Beacon Bay", "Nahoon",
    "Gonubie", "Mdantsane", "King Williams Town", "Queenstown", "Komani",
    "Grahamstown", "Makhanda", "Uitenhage", "Kariega", "Despatch", "Jeffreys Bay",
    "Port Alfred", "Butterworth", "Mthatha", "Bhisho", "Stutterheim", "Cathcart",
    "Cradock", "Graaff-Reinet", "Aliwal North", "Burgersdorp", "Steynsburg",
    "Engcobo", "Idutywa", "Kentani", "Lusikisiki", "Flagstaff", "Bizana",
    "Mount Frere", "Mount Ayliff", "Cofimvaba", "Tsomo", "Centane",
    "St Francis Bay", "Cape St Francis", "Hankey", "Patensie", "Humansdorp",
    "Kabega Park", "Sunridge Park", "Westering", "Charlo", "Sherwood",
    "Fairview", "Linton Grange", "Algoa Park", "Bethelsdorp", "Motherwell",
  ],
  "Free State": [
    "Bloemfontein CBD", "Westdene", "Dan Pienaar", "Universitas", "Brandwag", "Langenhoven Park",
    "Bayswater", "Arboretum", "Willows", "Botshabelo", "Thaba Nchu", "Welkom",
    "Virginia", "Odendaalsrus", "Sasolburg", "Parys", "Phuthaditjhaba", "Harrismith",
    "Bethlehem", "Kroonstad", "Heilbron", "Frankfort", "Reitz", "Vrede",
    "Warden", "Ficksburg", "Senekal", "Marquard", "Clocolan", "Ladybrand",
    "Fauresmith", "Trompsburg", "Smithfield", "Zastron", "Wepener",
    "Heidedal", "Mangaung", "Bochabela", "Rocklands", "Bayswater Park",
    "Hospital Park", "Pellissier", "Fichardt Park", "Wilgehof", "Naval Hill",
    "Hilton", "Ehrlich Park", "Generaal de Wet", "Wesburg", "Helicon Heights",
    "Vaalrivier", "Allanridge", "Henneman", "Theunissen", "Brandfort",
  ],
  "Limpopo": [
    "Polokwane CBD", "Bendor", "Penina Park", "Flora Park", "Tzaneen", "Phalaborwa",
    "Mokopane", "Bela-Bela", "Thohoyandou", "Burgersfort", "Giyani", "Louis Trichardt",
    "Makhado", "Musina", "Lephalale", "Nylstroom", "Modimolle", "Seshego",
    "Mankweng", "Mahwelereng", "Lebowakgomo", "Jane Furse", "Marble Hall",
    "Groblersdal", "Roedtan", "Naboomspruit", "Mookgophong", "Hoedspruit",
    "Letaba", "Duiwelskloof", "Modjadjiskloof", "Soekmekaar", "Vivo",
    "Alldays", "Tom Burke", "Steilloop", "Marken", "Bochum", "Senwabarwana",
    "Dendron", "Mphephu", "Sibasa", "Malamulele", "Levubu", "Tshilidzini",
    "Westernburg", "Eduan Park", "Ivydale", "Welgelegen", "Annadale",
    "Fauna Park", "Ivy Park", "Capricorn", "Sterpark", "Serala View",
  ],
  "Mpumalanga": [
    "Nelspruit CBD", "Mbombela", "White River", "Hazyview", "Sabie", "Lydenburg",
    "Witbank CBD", "eMalahleni", "Secunda", "Middelburg", "Standerton", "Ermelo",
    "Piet Retief", "Barberton", "Malelane", "Komatipoort", "Siyabuswa", "KwaMhlanga",
    "Mhluzi", "Kanyamazane", "Kabokweni", "Tekwane", "Schoemansdal",
    "Steelpoort", "Burgersfort", "Bushbuckridge", "Acornhoek", "Thulamahashe",
    "Kwaggafontein", "Verena", "Bronkhorstspruit", "Cullinan", "Refilwe",
    "Carolina", "Badplaas", "Chrissiesmeer", "Volksrust", "Wakkerstroom",
    "Amsterdam", "Dirkiesdorp", "Pongola", "Paulpietersburg",
    "Sonheuwel", "Stonehenge", "Sonpark", "West Acres", "Riverside Park",
    "Rocky Drift", "Steiltes", "Valencia Park", "Mhluzi", "Klarinet",
  ],
  "North West": [
    "Rustenburg CBD", "Tlhabane", "Boitekong", "Brits", "Hartbeespoort", "Potchefstroom",
    "Klerksdorp", "Stilfontein", "Orkney", "Mahikeng", "Mafikeng", "Lichtenburg",
    "Zeerust", "Vryburg", "Wolmaransstad", "Temba", "Ga-Rankuwa", "Mabopane",
    "Madibogo", "Coligny", "Sannieshof", "Schweizer-Reneke", "Bloemhof",
    "Christiana", "Hartswater", "Jan Kempdorp", "Warrenton", "Ottosdal",
    "Delareyville", "Itsoseng", "Letsopa", "Madikwe", "Swartruggens",
    "Koster", "Derby", "Lehurutshe", "Phokeng", "Marikana", "Bafokeng",
    "Mogwase", "Moruleng", "Tlapeng", "Mooinooi", "Magaliesburg",
    "Cashan", "Waterval East", "Geelhoutpark", "Safari Tuine", "Protea Park",
    "Tuscany Ridge", "Donkerhoek", "Tlhabane West", "Boitekong Extension",
  ],
  "Northern Cape": [
    "Kimberley CBD", "Galeshewe", "Roodepan", "Upington", "Kuruman", "Douglas",
    "De Aar", "Colesberg", "Springbok", "Pofadder", "Calvinia", "Carnarvon",
    "Victoria West", "Britstown", "Postmasburg", "Kathu", "Sishen", "Jan Kempdorp",
    "Hopetown", "Strydenburg", "Prieska", "Marydale", "Niekerkshoop", "Groblershoop",
    "Keimoes", "Kakamas", "Augrabies", "Riemvasmaak", "Onseepkans",
    "Garies", "Kamieskroon", "Port Nolloth", "Alexander Bay", "Aggeneys",
    "Loeriesfontein", "Brandvlei", "Williston", "Sutherland", "Fraserburg",
    "Hanover", "Richmond", "Petrusville", "Vanderkloof", "Philipstown",
    "Hadison Park", "Royldene", "Diamant Park", "Hillcrest", "Carters Glen",
    "Klipdrift", "Greenpoint", "Squarehill Park", "Memorial Road Area",
  ],
};
