/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuspendedRouteImport } from './routes/suspended'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RejectedRouteImport } from './routes/rejected'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SickNotesIndexRouteImport } from './routes/sick-notes.index'
import { Route as PrescriptionsIndexRouteImport } from './routes/prescriptions.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SickNotesNewRouteImport } from './routes/sick-notes.new'
import { Route as SickNotesIdRouteImport } from './routes/sick-notes.$id'
import { Route as PrescriptionsNewRouteImport } from './routes/prescriptions.new'
import { Route as PrescriptionsIdRouteImport } from './routes/prescriptions.$id'
import { Route as PatientsNewRouteImport } from './routes/patients.new'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppointmentsNewRouteImport } from './routes/appointments.new'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOutboxRouteImport } from './routes/admin.outbox'
import { Route as AdminModuleRouteImport } from './routes/admin.module'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminPracticesIndexRouteImport } from './routes/admin.practices.index'
import { Route as AdminPracticesPendingRouteImport } from './routes/admin.practices.pending'
import { Route as AdminPracticesIdRouteImport } from './routes/admin.practices.$id'

const SuspendedRoute = SuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RejectedRoute = RejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SickNotesIndexRoute = SickNotesIndexRouteImport.update({
  id: '/sick-notes/',
  path: '/sick-notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsIndexRoute = PrescriptionsIndexRouteImport.update({
  id: '/prescriptions/',
  path: '/prescriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SickNotesNewRoute = SickNotesNewRouteImport.update({
  id: '/sick-notes/new',
  path: '/sick-notes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SickNotesIdRoute = SickNotesIdRouteImport.update({
  id: '/sick-notes/$id',
  path: '/sick-notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsNewRoute = PrescriptionsNewRouteImport.update({
  id: '/prescriptions/new',
  path: '/prescriptions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsIdRoute = PrescriptionsIdRouteImport.update({
  id: '/prescriptions/$id',
  path: '/prescriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsNewRoute = AppointmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppointmentsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOutboxRoute = AdminOutboxRouteImport.update({
  id: '/admin/outbox',
  path: '/admin/outbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModuleRoute = AdminModuleRouteImport.update({
  id: '/admin/module',
  path: '/admin/module',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPracticesIndexRoute = AdminPracticesIndexRouteImport.update({
  id: '/admin/practices/',
  path: '/admin/practices/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPracticesPendingRoute = AdminPracticesPendingRouteImport.update({
  id: '/admin/practices/pending',
  path: '/admin/practices/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPracticesIdRoute = AdminPracticesIdRouteImport.update({
  id: '/admin/practices/$id',
  path: '/admin/practices/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/rejected': typeof RejectedRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/suspended': typeof SuspendedRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/module': typeof AdminModuleRoute
  '/admin/outbox': typeof AdminOutboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/prescriptions/$id': typeof PrescriptionsIdRoute
  '/prescriptions/new': typeof PrescriptionsNewRoute
  '/sick-notes/$id': typeof SickNotesIdRoute
  '/sick-notes/new': typeof SickNotesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/prescriptions/': typeof PrescriptionsIndexRoute
  '/sick-notes/': typeof SickNotesIndexRoute
  '/admin/practices/$id': typeof AdminPracticesIdRoute
  '/admin/practices/pending': typeof AdminPracticesPendingRoute
  '/admin/practices/': typeof AdminPracticesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/rejected': typeof RejectedRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/suspended': typeof SuspendedRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/module': typeof AdminModuleRoute
  '/admin/outbox': typeof AdminOutboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/prescriptions/$id': typeof PrescriptionsIdRoute
  '/prescriptions/new': typeof PrescriptionsNewRoute
  '/sick-notes/$id': typeof SickNotesIdRoute
  '/sick-notes/new': typeof SickNotesNewRoute
  '/admin': typeof AdminIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/prescriptions': typeof PrescriptionsIndexRoute
  '/sick-notes': typeof SickNotesIndexRoute
  '/admin/practices/$id': typeof AdminPracticesIdRoute
  '/admin/practices/pending': typeof AdminPracticesPendingRoute
  '/admin/practices': typeof AdminPracticesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/rejected': typeof RejectedRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/suspended': typeof SuspendedRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/module': typeof AdminModuleRoute
  '/admin/outbox': typeof AdminOutboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/prescriptions/$id': typeof PrescriptionsIdRoute
  '/prescriptions/new': typeof PrescriptionsNewRoute
  '/sick-notes/$id': typeof SickNotesIdRoute
  '/sick-notes/new': typeof SickNotesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/prescriptions/': typeof PrescriptionsIndexRoute
  '/sick-notes/': typeof SickNotesIndexRoute
  '/admin/practices/$id': typeof AdminPracticesIdRoute
  '/admin/practices/pending': typeof AdminPracticesPendingRoute
  '/admin/practices/': typeof AdminPracticesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/billing'
    | '/calendar'
    | '/change-password'
    | '/dashboard'
    | '/equipment'
    | '/inventory'
    | '/login'
    | '/pending'
    | '/register'
    | '/rejected'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/suspended'
    | '/admin/audit'
    | '/admin/module'
    | '/admin/outbox'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/appointments/new'
    | '/invite/$token'
    | '/patients/$id'
    | '/patients/new'
    | '/prescriptions/$id'
    | '/prescriptions/new'
    | '/sick-notes/$id'
    | '/sick-notes/new'
    | '/admin/'
    | '/patients/'
    | '/prescriptions/'
    | '/sick-notes/'
    | '/admin/practices/$id'
    | '/admin/practices/pending'
    | '/admin/practices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/billing'
    | '/calendar'
    | '/change-password'
    | '/dashboard'
    | '/equipment'
    | '/inventory'
    | '/login'
    | '/pending'
    | '/register'
    | '/rejected'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/suspended'
    | '/admin/audit'
    | '/admin/module'
    | '/admin/outbox'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/appointments/new'
    | '/invite/$token'
    | '/patients/$id'
    | '/patients/new'
    | '/prescriptions/$id'
    | '/prescriptions/new'
    | '/sick-notes/$id'
    | '/sick-notes/new'
    | '/admin'
    | '/patients'
    | '/prescriptions'
    | '/sick-notes'
    | '/admin/practices/$id'
    | '/admin/practices/pending'
    | '/admin/practices'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/billing'
    | '/calendar'
    | '/change-password'
    | '/dashboard'
    | '/equipment'
    | '/inventory'
    | '/login'
    | '/pending'
    | '/register'
    | '/rejected'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/suspended'
    | '/admin/audit'
    | '/admin/module'
    | '/admin/outbox'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/appointments/new'
    | '/invite/$token'
    | '/patients/$id'
    | '/patients/new'
    | '/prescriptions/$id'
    | '/prescriptions/new'
    | '/sick-notes/$id'
    | '/sick-notes/new'
    | '/admin/'
    | '/patients/'
    | '/prescriptions/'
    | '/sick-notes/'
    | '/admin/practices/$id'
    | '/admin/practices/pending'
    | '/admin/practices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRouteWithChildren
  BillingRoute: typeof BillingRoute
  CalendarRoute: typeof CalendarRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  EquipmentRoute: typeof EquipmentRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  RegisterRoute: typeof RegisterRoute
  RejectedRoute: typeof RejectedRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  SuspendedRoute: typeof SuspendedRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminModuleRoute: typeof AdminModuleRoute
  AdminOutboxRoute: typeof AdminOutboxRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PatientsIdRoute: typeof PatientsIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  PrescriptionsIdRoute: typeof PrescriptionsIdRoute
  PrescriptionsNewRoute: typeof PrescriptionsNewRoute
  SickNotesIdRoute: typeof SickNotesIdRoute
  SickNotesNewRoute: typeof SickNotesNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  PrescriptionsIndexRoute: typeof PrescriptionsIndexRoute
  SickNotesIndexRoute: typeof SickNotesIndexRoute
  AdminPracticesIdRoute: typeof AdminPracticesIdRoute
  AdminPracticesPendingRoute: typeof AdminPracticesPendingRoute
  AdminPracticesIndexRoute: typeof AdminPracticesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suspended': {
      id: '/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof SuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejected': {
      id: '/rejected'
      path: '/rejected'
      fullPath: '/rejected'
      preLoaderRoute: typeof RejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sick-notes/': {
      id: '/sick-notes/'
      path: '/sick-notes'
      fullPath: '/sick-notes/'
      preLoaderRoute: typeof SickNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions/': {
      id: '/prescriptions/'
      path: '/prescriptions'
      fullPath: '/prescriptions/'
      preLoaderRoute: typeof PrescriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sick-notes/new': {
      id: '/sick-notes/new'
      path: '/sick-notes/new'
      fullPath: '/sick-notes/new'
      preLoaderRoute: typeof SickNotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sick-notes/$id': {
      id: '/sick-notes/$id'
      path: '/sick-notes/$id'
      fullPath: '/sick-notes/$id'
      preLoaderRoute: typeof SickNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions/new': {
      id: '/prescriptions/new'
      path: '/prescriptions/new'
      fullPath: '/prescriptions/new'
      preLoaderRoute: typeof PrescriptionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions/$id': {
      id: '/prescriptions/$id'
      path: '/prescriptions/$id'
      fullPath: '/prescriptions/$id'
      preLoaderRoute: typeof PrescriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/new': {
      id: '/appointments/new'
      path: '/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof AppointmentsNewRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/outbox': {
      id: '/admin/outbox'
      path: '/admin/outbox'
      fullPath: '/admin/outbox'
      preLoaderRoute: typeof AdminOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/module': {
      id: '/admin/module'
      path: '/admin/module'
      fullPath: '/admin/module'
      preLoaderRoute: typeof AdminModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/practices/': {
      id: '/admin/practices/'
      path: '/admin/practices'
      fullPath: '/admin/practices/'
      preLoaderRoute: typeof AdminPracticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/practices/pending': {
      id: '/admin/practices/pending'
      path: '/admin/practices/pending'
      fullPath: '/admin/practices/pending'
      preLoaderRoute: typeof AdminPracticesPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/practices/$id': {
      id: '/admin/practices/$id'
      path: '/admin/practices/$id'
      fullPath: '/admin/practices/$id'
      preLoaderRoute: typeof AdminPracticesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppointmentsRouteChildren {
  AppointmentsNewRoute: typeof AppointmentsNewRoute
}

const AppointmentsRouteChildren: AppointmentsRouteChildren = {
  AppointmentsNewRoute: AppointmentsNewRoute,
}

const AppointmentsRouteWithChildren = AppointmentsRoute._addFileChildren(
  AppointmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRouteWithChildren,
  BillingRoute: BillingRoute,
  CalendarRoute: CalendarRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  EquipmentRoute: EquipmentRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  RegisterRoute: RegisterRoute,
  RejectedRoute: RejectedRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  SuspendedRoute: SuspendedRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminModuleRoute: AdminModuleRoute,
  AdminOutboxRoute: AdminOutboxRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  InviteTokenRoute: InviteTokenRoute,
  PatientsIdRoute: PatientsIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  PrescriptionsIdRoute: PrescriptionsIdRoute,
  PrescriptionsNewRoute: PrescriptionsNewRoute,
  SickNotesIdRoute: SickNotesIdRoute,
  SickNotesNewRoute: SickNotesNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  PrescriptionsIndexRoute: PrescriptionsIndexRoute,
  SickNotesIndexRoute: SickNotesIndexRoute,
  AdminPracticesIdRoute: AdminPracticesIdRoute,
  AdminPracticesPendingRoute: AdminPracticesPendingRoute,
  AdminPracticesIndexRoute: AdminPracticesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
